export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const FAIL_SEARCH_RESULTS = 'FAIL_SEARCH_RESULTS';
export const SET_LOCATION = 'SET_LOCATION';